# Generated by Django 4.2.4 on 2023-08-29 22:34

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UrunGruplari",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Grup_Adi", models.CharField(max_length=255, unique=True)),
            ],
            options={"verbose_name_plural": "Urun Grupları",},
        ),
        migrations.CreateModel(
            name="Stok",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Urun_Adi", models.CharField(max_length=10)),
                ("Barkod", models.PositiveBigIntegerField(default=0, unique=True)),
                (
                    "Tutar",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("Stok_Durumu", models.BooleanField(default=True)),
                ("Ekleme_Tarih", models.DateTimeField(auto_now_add=True)),
                ("guncelleme_tarihi", models.DateTimeField(auto_now=True)),
                (
                    "Grup",
                    models.ManyToManyField(
                        blank=True, null=True, to="stok.urungruplari"
                    ),
                ),
            ],
            options={"verbose_name_plural": "Stok urunleri",},
        ),
        migrations.CreateModel(
            name="SepetUrun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("miktar", models.PositiveIntegerField(default=1)),
                (
                    "urun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stok.stok"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
