# Generated by Django 4.2.4 on 2023-08-29 23:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stok", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stok",
            name="Tutar",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=44,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stok", name="Urun_Adi", field=models.CharField(max_length=255),
        ),
    ]
