# Generated by Django 4.2.4 on 2023-08-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stok", "0002_alter_stok_tutar_alter_stok_urun_adi"),
    ]

    operations = [
        migrations.AddField(
            model_name="stok",
            name="Urun_Genel",
            field=models.CharField(
                blank=True, editable=False, max_length=500, null=True
            ),
        ),
    ]
