# Generated by Django 4.2.4 on 2023-08-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stok", "0003_stok_urun_genel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stok",
            name="Barkod",
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
