# Generated by Django 4.2.4 on 2023-08-31 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stok", "0004_alter_stok_barkod"),
    ]

    operations = [
        migrations.AddField(
            model_name="stok", name="Favori", field=models.BooleanField(default=False),
        ),
    ]
