# Generated by Django 4.2.4 on 2023-09-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stok", "0005_stok_favori"),
    ]

    operations = [
        migrations.AddField(
            model_name="stok", name="Oto_Sil", field=models.BooleanField(default=False),
        ),
    ]
