# Generated by Django 4.2.4 on 2023-09-01 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stok", "0006_stok_oto_sil"),
    ]

    operations = [
        migrations.CreateModel(
            name="Liste_Grup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Grup_Adi", models.CharField(max_length=255, unique=True)),
            ],
            options={"verbose_name_plural": "Liste Favori Grupları",},
        ),
        migrations.CreateModel(
            name="Musteri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim_soyisim", models.CharField(max_length=255)),
                ("Cep_Telefonu", models.PositiveBigIntegerField(max_length=10)),
                (
                    "borc",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("aciklama", models.TextField(blank=True, null=True)),
                ("Ekleme_Tarih", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BorcHareketi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tutar", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tarih", models.DateTimeField(auto_now_add=True)),
                ("aciklama", models.CharField(max_length=255)),
                ("onceki_borc", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "musteri",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stok.musteri"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="stok",
            name="Liste_grup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stok.liste_grup",
            ),
        ),
    ]
