# Generated by Django 4.2.4 on 2023-09-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stok", "0007_liste_grup_musteri_borchareketi_stok_liste_grup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musteri",
            name="Cep_Telefonu",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name="stok",
            name="Grup",
            field=models.ManyToManyField(blank=True, to="stok.urungruplari"),
        ),
    ]
