# Generated by Django 4.2.4 on 2026-08-30 17:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    """Stok adedi, stok hareketleri ve kirtasiye satis kayitlari.

    NOT: Django bu dosyayi uretirken Musteri.Cep_Telefonu icin de bir
    AlterField ekliyordu (modelde null=True, migration 0008'de NOT NULL —
    onceden var olan uyumsuzluk). Planlanmamis oldugu icin ELLE cikarildi.
    """


    dependencies = [
        ("stok", "0009_borchareketi_aciklama_uzun"),
    ]

    operations = [
        migrations.CreateModel(
            name="Satis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "toplam",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Toplam",
                    ),
                ),
                (
                    "nakit_tutar",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Nakit"
                    ),
                ),
                (
                    "kart_tutar",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Kredi kartı",
                    ),
                ),
                (
                    "borc_tutar",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Borca yazılan",
                    ),
                ),
                (
                    "odeme_turu",
                    models.CharField(
                        choices=[
                            ("nakit", "Nakit"),
                            ("kart", "Kredi kartı"),
                            ("parcali", "Parçalı"),
                            ("borc", "Borca yazıldı"),
                        ],
                        default="nakit",
                        max_length=16,
                        verbose_name="Ödeme türü",
                    ),
                ),
                (
                    "kalem_adedi",
                    models.PositiveIntegerField(default=0, verbose_name="Kalem adedi"),
                ),
                (
                    "kasiyer",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Kasiyer"
                    ),
                ),
                ("notlar", models.TextField(blank=True, verbose_name="Not")),
                (
                    "tarih",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Tarih"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kırtasiye satışı",
                "verbose_name_plural": "Kırtasiye satışları",
                "ordering": ("-tarih",),
            },
        ),
        migrations.AddField(
            model_name="stok",
            name="stok_adedi",
            field=models.IntegerField(
                blank=True,
                help_text="Boş bırakılırsa bu ürün için stok takibi yapılmaz.",
                null=True,
                verbose_name="Stok adedi",
            ),
        ),
        migrations.CreateModel(
            name="StokHareketi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tur",
                    models.CharField(
                        choices=[
                            ("satis", "Satış"),
                            ("giris", "Mal girişi"),
                            ("duzeltme", "Sayım düzeltmesi"),
                            ("iade", "İade"),
                        ],
                        max_length=16,
                        verbose_name="Hareket türü",
                    ),
                ),
                ("miktar", models.IntegerField(verbose_name="Miktar")),
                (
                    "onceki_adet",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Önceki adet"
                    ),
                ),
                (
                    "sonraki_adet",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Sonraki adet"
                    ),
                ),
                (
                    "aciklama",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Açıklama"
                    ),
                ),
                (
                    "kullanici",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Kullanıcı"
                    ),
                ),
                (
                    "tarih",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Tarih"
                    ),
                ),
                (
                    "urun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hareketler",
                        to="stok.stok",
                        verbose_name="Ürün",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stok hareketi",
                "verbose_name_plural": "Stok hareketleri",
                "ordering": ("-tarih",),
            },
        ),
        migrations.CreateModel(
            name="SatisSatiri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("urun_adi", models.CharField(max_length=255, verbose_name="Ürün adı")),
                (
                    "birim_fiyat",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Birim fiyat"
                    ),
                ),
                (
                    "miktar",
                    models.PositiveIntegerField(default=1, verbose_name="Miktar"),
                ),
                (
                    "satis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="satirlar",
                        to="stok.satis",
                    ),
                ),
                (
                    "urun",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stok.stok",
                        verbose_name="Ürün",
                    ),
                ),
            ],
            options={
                "verbose_name": "Satış satırı",
                "verbose_name_plural": "Satış satırları",
            },
        ),
        migrations.AddField(
            model_name="satis",
            name="borc_musteri",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kirtasiye_satislari",
                to="stok.musteri",
                verbose_name="Borç yazılan müşteri",
            ),
        ),
    ]
