# Generated by Django 4.2.4 on 2026-08-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    """Satisa indirim tutari.

    NOT: makemigrations bunun yaninda Musteri.Cep_Telefonu icin de bir
    AlterField uretiyor (onceden var olan uyumsuzluk). Elle cikarildi.
    """


    dependencies = [
        ("stok", "0010_satis_stok_hareketi"),
    ]

    operations = [
        migrations.AddField(
            model_name="satis",
            name="indirim_tutari",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Kasada elle verilen özel indirim. Ara toplam = toplam + indirim.",
                max_digits=12,
                verbose_name="İndirim",
            ),
        ),
    ]
