# Generated by Django 4.2.4 on 2026-08-30 08:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import kahve.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kahve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=120, verbose_name="Kahve adı")),
                ("aciklama", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "icindekiler",
                    models.TextField(
                        blank=True,
                        help_text="Her satıra bir malzeme yaz.",
                        verbose_name="İçindekiler",
                    ),
                ),
                (
                    "fiyat",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Fiyat (₺)",
                    ),
                ),
                (
                    "gorsel",
                    models.ImageField(
                        blank=True, null=True, upload_to="kahve/", verbose_name="Görsel"
                    ),
                ),
                (
                    "sira",
                    models.PositiveIntegerField(default=0, verbose_name="Sıralama"),
                ),
                (
                    "aktif",
                    models.BooleanField(default=True, verbose_name="Menüde görünsün"),
                ),
                (
                    "hediye_gecerli",
                    models.BooleanField(
                        default=True,
                        help_text="Kapatırsan bu kahve hediye olarak verilemez.",
                        verbose_name="Hediye ile alınabilir",
                    ),
                ),
                (
                    "eklenme_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Eklenme tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kahve",
                "verbose_name_plural": "Kahveler",
                "ordering": ("sira", "ad"),
            },
        ),
        migrations.CreateModel(
            name="KahveAyar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "isletme_adi",
                    models.CharField(
                        default="Atlas Kahve",
                        max_length=120,
                        verbose_name="İşletme adı",
                    ),
                ),
                (
                    "slogan",
                    models.CharField(
                        blank=True,
                        default="Beş kahve içenin altıncısı bizden",
                        max_length=200,
                        verbose_name="Slogan",
                    ),
                ),
                (
                    "hediye_icin_kahve",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Kaç kahve içince 1 kahve hediye olsun?",
                        verbose_name="Hediye için gereken kahve",
                    ),
                ),
                (
                    "gecerlilik_gun",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="İçilen bir kahve kaç gün boyunca hediye sayacında kalsın? Süre dolunca sayaçtan düşer.",
                        verbose_name="Kahve geçerlilik süresi (gün)",
                    ),
                ),
                (
                    "firebase_api_key",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Firebase Web API Key"
                    ),
                ),
                (
                    "firebase_auth_domain",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Firebase Auth Domain"
                    ),
                ),
                (
                    "firebase_project_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Firebase Project ID"
                    ),
                ),
                (
                    "firebase_app_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Firebase App ID"
                    ),
                ),
                (
                    "firebase_sender_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Firebase Sender ID"
                    ),
                ),
                (
                    "firebase_storage_bucket",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Firebase Storage Bucket",
                    ),
                ),
                (
                    "cron_anahtari",
                    models.CharField(
                        default=kahve.models._anahtar_uret,
                        help_text="Günlük temizlik URL'inde kullanılır. Kimseyle paylaşma.",
                        max_length=64,
                        verbose_name="Cron anahtarı",
                    ),
                ),
                (
                    "mobil_api_anahtari",
                    models.CharField(
                        default=kahve.models._anahtar_uret,
                        help_text="Mobil uygulama her istekte 'X-Kahve-Key' başlığında bu değeri gönderir.",
                        max_length=64,
                        verbose_name="Mobil API anahtarı",
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kahve Ayarı",
                "verbose_name_plural": "Kahve Ayarları",
            },
        ),
        migrations.CreateModel(
            name="KahveMusteri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firebase_uid",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        unique=True,
                        verbose_name="Firebase UID",
                    ),
                ),
                ("ad_soyad", models.CharField(max_length=150, verbose_name="Ad soyad")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-posta"
                    ),
                ),
                (
                    "telefon",
                    models.CharField(blank=True, max_length=32, verbose_name="Telefon"),
                ),
                (
                    "kod",
                    models.CharField(
                        default=kahve.models._musteri_kodu_uret,
                        max_length=32,
                        unique=True,
                        verbose_name="Barkod no",
                    ),
                ),
                (
                    "qr_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="QR anahtarı",
                    ),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "kayit_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Kayıt tarihi"
                    ),
                ),
                (
                    "son_gorulme",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son görülme"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kahve Müşterisi",
                "verbose_name_plural": "Kahve Müşterileri",
                "ordering": ("-kayit_tarihi",),
            },
        ),
        migrations.CreateModel(
            name="KahveIcim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kahve_adi",
                    models.CharField(
                        blank=True,
                        help_text="Kahve silinse de geçmiş bozulmasın diye.",
                        max_length=120,
                    ),
                ),
                (
                    "fiyat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("aktif", "Sayacta"),
                            ("harcandi", "Hediyeye sayıldı"),
                            ("doldu", "Süresi doldu"),
                            ("hediye", "Hediye kahve"),
                        ],
                        default="aktif",
                        max_length=16,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "tarih",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Tarih"
                    ),
                ),
                (
                    "son_gecerlilik",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son geçerlilik"
                    ),
                ),
                (
                    "ekleyen",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Ekleyen personel"
                    ),
                ),
                (
                    "kahve",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="icimler",
                        to="kahve.kahve",
                    ),
                ),
                (
                    "musteri",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="icimler",
                        to="kahve.kahvemusteri",
                        verbose_name="Müşteri",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kahve İçimi",
                "verbose_name_plural": "Kahve İçimleri",
                "ordering": ("-tarih",),
            },
        ),
        migrations.CreateModel(
            name="HediyeKahve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("bekliyor", "Kullanılmayı bekliyor"),
                            ("kullanildi", "Kullanıldı"),
                        ],
                        default="bekliyor",
                        max_length=16,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "kazanma_tarihi",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Kazanma tarihi"
                    ),
                ),
                (
                    "kullanma_tarihi",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Kullanma tarihi"
                    ),
                ),
                (
                    "kullanilan_icim",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hediye_kaydi",
                        to="kahve.kahveicim",
                    ),
                ),
                (
                    "musteri",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hediyeler",
                        to="kahve.kahvemusteri",
                        verbose_name="Müşteri",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hediye Kahve",
                "verbose_name_plural": "Hediye Kahveler",
                "ordering": ("-kazanma_tarihi",),
            },
        ),
        migrations.AddIndex(
            model_name="kahveicim",
            index=models.Index(
                fields=["durum", "son_gecerlilik"], name="kahve_kahve_durum_130102_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kahveicim",
            index=models.Index(
                fields=["musteri", "durum"], name="kahve_kahve_musteri_ae4eff_idx"
            ),
        ),
    ]
