# Generated by Django 4.2.4 on 2026-08-30 10:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("kahve", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KahveSatis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "toplam",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Toplam",
                    ),
                ),
                (
                    "nakit_tutar",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Nakit"
                    ),
                ),
                (
                    "kart_tutar",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Kredi kartı",
                    ),
                ),
                (
                    "odeme_turu",
                    models.CharField(
                        choices=[
                            ("nakit", "Nakit"),
                            ("kart", "Kredi kartı"),
                            ("parcali", "Parçalı"),
                        ],
                        default="nakit",
                        max_length=16,
                        verbose_name="Ödeme türü",
                    ),
                ),
                (
                    "fincan_adedi",
                    models.PositiveIntegerField(default=0, verbose_name="Fincan adedi"),
                ),
                (
                    "hediye_adedi",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Hediye ile verilen"
                    ),
                ),
                (
                    "tarih",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Tarih"
                    ),
                ),
                (
                    "kasiyer",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Kasiyer"
                    ),
                ),
                (
                    "musteri",
                    models.ForeignKey(
                        blank=True,
                        help_text="Kartsız satışta boş kalır.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="satislar",
                        to="kahve.kahvemusteri",
                        verbose_name="Müşteri",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kahve Satışı",
                "verbose_name_plural": "Kahve Satışları",
                "ordering": ("-tarih",),
            },
        ),
        migrations.AddField(
            model_name="kahveicim",
            name="satis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="icimler",
                to="kahve.kahvesatis",
                verbose_name="Satış",
            ),
        ),
        migrations.AddIndex(
            model_name="kahvesatis",
            index=models.Index(fields=["-tarih"], name="kahve_kahve_tarih_5c228e_idx"),
        ),
    ]
