# Generated by Django 4.2.4 on 2026-08-30 10:44

from django.db import migrations, models


def eski_urunler_damga_versin(apps, schema_editor):
    """Bu alan eklenmeden once satilan her urun damga veriyordu.

    Yeni alanin varsayilani False; mevcut urunleri True yapmazsak migration
    sonrasi hicbir urun damga vermez ve sadakat sistemi sessizce durur.
    """
    Kahve = apps.get_model("kahve", "Kahve")
    Kahve.objects.update(damga_veriyor=True)


def geri_al(apps, schema_editor):
    pass  # alan zaten kaldirilacak, yapacak bir sey yok


class Migration(migrations.Migration):

    dependencies = [
        ("kahve", "0002_kahvesatis_kahveicim_satis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kahve",
            name="damga_veriyor",
            field=models.BooleanField(
                default=False,
                help_text="Açıksa bu ürün satıldığında müşterinin sayacına damga eklenir. Kurabiye, su gibi hediye kazandırmayan ürünlerde kapalı bırakın.",
                verbose_name="Hediye sayacına +1",
            ),
        ),
        migrations.AlterField(
            model_name="kahve",
            name="hediye_gecerli",
            field=models.BooleanField(
                default=True,
                help_text="Kapatırsan bu ürün hediye olarak verilemez.",
                verbose_name="Hediye ile alınabilir",
            ),
        ),
        migrations.AlterField(
            model_name="kahveicim",
            name="durum",
            field=models.CharField(
                choices=[
                    ("aktif", "Sayacta"),
                    ("harcandi", "Hediyeye sayıldı"),
                    ("doldu", "Süresi doldu"),
                    ("hediye", "Hediye kahve"),
                    ("sayilmaz", "Sayaca girmez"),
                ],
                default="aktif",
                max_length=16,
                verbose_name="Durum",
            ),
        ),
        migrations.RunPython(eski_urunler_damga_versin, geri_al),
    ]
