# Generated by Django 4.2.4 on 2026-08-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kahve", "0003_kahve_damga_veriyor_alter_kahve_hediye_gecerli_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kahvesatis",
            name="fincan_adedi",
            field=models.PositiveIntegerField(default=0, verbose_name="Kalem adedi"),
        ),
    ]
