# Generated by Django 4.2.4 on 2026-08-30 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kahve", "0004_alter_kahvesatis_fincan_adedi"),
    ]

    operations = [
        migrations.CreateModel(
            name="KahveKategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ad",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="Kategori adı"
                    ),
                ),
                (
                    "sira",
                    models.PositiveIntegerField(default=0, verbose_name="Sıralama"),
                ),
                (
                    "aktif",
                    models.BooleanField(default=True, verbose_name="Menüde görünsün"),
                ),
            ],
            options={
                "verbose_name": "Kahve Kategorisi",
                "verbose_name_plural": "Kahve Kategorileri",
                "ordering": ("sira", "ad"),
            },
        ),
        migrations.AlterModelOptions(
            name="kahve",
            options={
                "ordering": ("kategori__sira", "sira", "ad"),
                "verbose_name": "Kahve",
                "verbose_name_plural": "Kahveler",
            },
        ),
        migrations.AddField(
            model_name="kahve",
            name="kategori",
            field=models.ForeignKey(
                blank=True,
                help_text="Boş bırakılırsa menüde 'Diğer' başlığı altında görünür.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="urunler",
                to="kahve.kahvekategori",
                verbose_name="Kategori",
            ),
        ),
    ]
