# Generated by Django 4.2.4 on 2026-08-30 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # Sadece stok.Musteri tablosunun var olmasi gerekiyor; 0009 yeterli.
        # (Ciplak makemigrations burada 0010_alter_musteri_cep_telefonu uretiyor —
        #  planlanmamis bir degisiklik, o yuzden ona bagimli olmuyoruz.)
        ("stok", "0009_borchareketi_aciklama_uzun"),
        ("kahve", "0006_isletme_adi_atlas_coffee"),
    ]

    operations = [
        migrations.AddField(
            model_name="kahvesatis",
            name="borc_musteri",
            field=models.ForeignKey(
                blank=True,
                help_text="Ödeme türü 'Borca yazıldı' ise dolu olur. Kırtasiye tarafındaki müşteri listesi.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kahve_satislari",
                to="stok.musteri",
                verbose_name="Borç yazılan müşteri",
            ),
        ),
        migrations.AlterField(
            model_name="kahvesatis",
            name="odeme_turu",
            field=models.CharField(
                choices=[
                    ("nakit", "Nakit"),
                    ("kart", "Kredi kartı"),
                    ("parcali", "Parçalı"),
                    ("borc", "Borca yazıldı"),
                ],
                default="nakit",
                max_length=16,
                verbose_name="Ödeme türü",
            ),
        ),
    ]
