# Generated by Django 4.2.4 on 2026-08-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kahve", "0007_kahvesatis_borc_musteri_alter_kahvesatis_odeme_turu"),
    ]

    operations = [
        migrations.AddField(
            model_name="kahvesatis",
            name="urunler",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Satılanlar"
            ),
        ),
    ]
