# Generated by Django 4.2.4 on 2026-08-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kahve", "0008_kahvesatis_urunler"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kahve",
            options={
                "ordering": (
                    models.OrderBy(models.F("kategori__sira"), nulls_last=True),
                    "sira",
                    "ad",
                ),
                "verbose_name": "Kahve",
                "verbose_name_plural": "Kahveler",
            },
        ),
    ]
