# Generated by Django 4.2.4 on 2026-08-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kahve", "0009_kahve_siralama_nulls_last"),
    ]

    operations = [
        migrations.AddField(
            model_name="kahvesatis",
            name="indirim_tutari",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Kasada elle verilen özel indirim.",
                max_digits=10,
                verbose_name="İndirim",
            ),
        ),
    ]
